### ISSUE TITLE
UpdateField方法-新增字段Option未生效

### ISSUE THREAD

**Issue by Relakkes** [larksuite/project-oapi-sdk-golang#6]
### 业务场景
调用[`更新自定义字段`](https://project.feishu.cn/b/helpcenter/1p8d7djs/tcu33puw)接口，对字段进行option新增操作.
在field option已经添加一个option的情况下，进行子option新增操作

### 预期结果
新增的option，比如上面示例中的`child level 3 field`能够添加成功。

### 实际结果
接口返回200，但是实际并没有更新option成功

### 请求json

```json
{
    "field_key": "field_875d91",
    "field_value": [
        {
            "label": "parent level 1 field",
            "value": "8lh63yaf7", // 已经存在的option
            "action": 1, 
            "children": [
                {
                    "label": "child level 3 field", // 新增option
                    "value": "",
                    "action": 0,
                    "children": null
                }
            ]
        }
    ]
}
```

### request id
202404160648063D968BAAF9EB983614E3

**Comment by heguiyan** [comment]
https://project.larkoffice.com/b/helpcenter/1p8d7djs/tcu33puw
![image](https://github.com/larksuite/project-oapi-sdk-golang/assets/151699856/ea466960-fad8-49b8-ad74-663858083b03)
![image](https://github.com/larksuite/project-oapi-sdk-golang/assets/151699856/727a67ff-a041-4006-9973-ab6afda392aa)
![image](https://github.com/larksuite/project-oapi-sdk-golang/assets/151699856/9d02830d-825b-41cb-8026-eb5fedd18a78)
